name:                mini-state
version:             0.1.0.2
github:              "lsund/mini-state"
license:             BSD3
author:              "Ludvig Sundstrom"
maintainer:          "lud.sund@gmail.com"
copyright:           "2022 Ludvig Sundstrom"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/lsund/mini-state#readme>

dependencies:
- base >= 4.7 && < 5
- microlens
- microlens-th
- text
- aeson
- directory
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
