{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RankNTypes        #-}
{-# LANGUAGE TemplateHaskell   #-}

module IO.Loader where

import           Lens.Micro.TH

type Linker a b c = Maybe [a] -> b -> Either String c

-- A loader is a specification how to load a table of type `c`.
-- Type c is generated by referencing type `a` from type `b`.
-- how the reference is made is determined by the Linker
data Loader a b c
  = Loader
      { _sourceFile :: FilePath
      , _payload    :: Maybe [a]
      , _linker     :: Linker a b c
      }

makeLenses ''Loader

